# Generated by Django 2.0 on 2019-06-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_list', '0003_auto_20190603_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_list',
            name='vegetable',
            field=models.BooleanField(default=False),
        ),
    ]
