# Generated by Django 2.0 on 2019-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_remove_origin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to='', width_field='width'),
        ),
    ]
