# Generated by Django 2.0 on 2019-06-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0005_auto_20190601_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
